repos:
  - hooks:
    - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
        - id: isort
          args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
        - id: black
          language_version: python3.8

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.254"
    hooks:
        - id: ruff
          args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.1"
    hooks:
        - id: mypy
