repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
    - id: mdformat

  - hooks:
    - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.0.0

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    - id: ruff
      args: [ --fix]
    - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
        - id: mypy
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["@.codespellrc"]
