site_name: "AIPOSE"
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - json

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature: true
            search_path: ["."]

  - search
  - mermaid2:
      version: '9.4.3'
      arguments:
        theme: 'dark'
        themeVariables:
          primaryColor: '#BB2528'
          primaryTextColor: '#fff'
          primaryBorderColor: '#7C0000'
          lineColor: '#F8B229'
          secondaryColor: '#006100'
          tertiaryColor: '#fff'
            
nav:
- Home: index.md
- Usage: usage.md
- Frame Manager: frame_manager_availables.md
- Models: models.md
