name: Create release

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: "Create release"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pipe-cd/actions-gh-release@v2.3.4
        with:
          release_file: '**/CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}
